//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nikan.Common.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nikan.Common.Resource.MessageResource", typeof(MessageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اجازه دسترسی.
        /// </summary>
        public static string AllowAccess {
            get {
                return ResourceManager.GetString("AllowAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فقط مجاز به وار کردن اعداد می باشید.
        /// </summary>
        public static string AllowOnlyNumbers {
            get {
                return ResourceManager.GetString("AllowOnlyNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انصراف.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغییر کلمه عبور.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تایید حذف .
        /// </summary>
        public static string ConfirmRecordDeletion {
            get {
                return ResourceManager.GetString("ConfirmRecordDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات تماس.
        /// </summary>
        public static string ContactInformation {
            get {
                return ResourceManager.GetString("ContactInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وارد کردن یکی از موارد تماس برای آگهی الزمی می باشد..
        /// </summary>
        public static string ContactRequiredMessage {
            get {
                return ResourceManager.GetString("ContactRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وارد نمودن توضیحات برای عدم تایید الزامی می باشد.
        /// </summary>
        public static string CreditBodyIsRequired {
            get {
                return ResourceManager.GetString("CreditBodyIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلمه عبور فعلی صحیح نمی باشد..
        /// </summary>
        public static string CurrentPasswordIsIncorrect {
            get {
                return ResourceManager.GetString("CurrentPasswordIsIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملیات حذف با موفقیت انجام گردید..
        /// </summary>
        public static string Deleted {
            get {
                return ResourceManager.GetString("Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملیات حذف.
        /// </summary>
        public static string DeletedAction {
            get {
                return ResourceManager.GetString("DeletedAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیا میخواهید رکورد {0}را حذف کنید.
        /// </summary>
        public static string DeleteRecord {
            get {
                return ResourceManager.GetString("DeleteRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد وارد شده تکراری می باشد.
        /// </summary>
        public static string DuplicateCode {
            get {
                return ResourceManager.GetString("DuplicateCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره کارگاه وارد شده قبلا ثبت شده است.
        /// </summary>
        public static string DuplicateCompanyNumber {
            get {
                return ResourceManager.GetString("DuplicateCompanyNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس ایمیل وارد شده قبلا استفاده شده است.
        /// </summary>
        public static string DuplicateEmail {
            get {
                return ResourceManager.GetString("DuplicateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای این کارجو قبلا فرم معرفی نامه  صادر شده است.
        /// </summary>
        public static string DuplicateFormIntroducingToWork {
            get {
                return ResourceManager.GetString("DuplicateFormIntroducingToWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره نامه وارد شده تکراری می باشد.
        /// </summary>
        public static string DuplicateFormIntroducingToWorkCode {
            get {
                return ResourceManager.GetString("DuplicateFormIntroducingToWorkCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره همراه وارد شده قبلا استفاده شده است.
        /// </summary>
        public static string DuplicateMobile {
            get {
                return ResourceManager.GetString("DuplicateMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد ملی وارد شده تکراری می باشد..
        /// </summary>
        public static string DuplicateNationalCode {
            get {
                return ResourceManager.GetString("DuplicateNationalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مسیر وارد شده تکراری می باشد.
        /// </summary>
        public static string DuplicatePath {
            get {
                return ResourceManager.GetString("DuplicatePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان وارد شده تکراری می باشد.
        /// </summary>
        public static string DuplicateTitle {
            get {
                return ResourceManager.GetString("DuplicateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملیات ویرایش.
        /// </summary>
        public static string EditAction {
            get {
                return ResourceManager.GetString("EditAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای ثبت نام شماره همراه یا آدرس ایمیل الزامی می باشد.
        /// </summary>
        public static string EmailOrMobileRequiredForRegisteration {
            get {
                return ResourceManager.GetString("EmailOrMobileRequiredForRegisteration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آگهی استخدام.
        /// </summary>
        public static string EmploymentInfo {
            get {
                return ResourceManager.GetString("EmploymentInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات را به صورت کامل وارد نمائید.
        /// </summary>
        public static string EnterInformationRequired {
            get {
                return ResourceManager.GetString("EnterInformationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطایی در اجرای عملیات رخ داده است.
        /// </summary>
        public static string ErrorinAction {
            get {
                return ResourceManager.GetString("ErrorinAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا.
        /// </summary>
        public static string ErrorSystem {
            get {
                return ResourceManager.GetString("ErrorSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در آزمایش پیکربندی ایمیل.
        /// </summary>
        public static string FailSendEmailForMailSettings {
            get {
                return ResourceManager.GetString("FailSendEmailForMailSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس ایمیل وارد شده نامعتبر می باشد.
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره همراه وارد شده نامعتبر می باشد.
        /// </summary>
        public static string InvalidMobile {
            get {
                return ResourceManager.GetString("InvalidMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیا مایل به حذف این آیتم هستدید؟.
        /// </summary>
        public static string IsDeleteItem {
            get {
                return ResourceManager.GetString("IsDeleteItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیا مایل به حذف سطر جاری هستدید؟.
        /// </summary>
        public static string IsDeleteRow {
            get {
                return ResourceManager.GetString("IsDeleteRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در ورود.
        /// </summary>
        public static string LoginError {
            get {
                return ResourceManager.GetString("LoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات وارد شده معتبر نیستند. لطفا مجددا سعی کنید..
        /// </summary>
        public static string LoginOnFailureMessage {
            get {
                return ResourceManager.GetString("LoginOnFailureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام مدیر عامل یا مسئول استخدام ضرروی می باشد.جهت صدور فرم معرفی نامه برای کاربر.
        /// </summary>
        public static string MangerNameRequiredMessage {
            get {
                return ResourceManager.GetString("MangerNameRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطای اعتبارسنجی.
        /// </summary>
        public static string ModelStateError {
            get {
                return ResourceManager.GetString("ModelStateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطای اعتبارسنجی.
        /// </summary>
        public static string ModelValidError {
            get {
                return ResourceManager.GetString("ModelValidError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد ملی وارد شده نامعتبر می باشد..
        /// </summary>
        public static string NationalCodeInValid {
            get {
                return ResourceManager.GetString("NationalCodeInValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد ملی الزامی می باشد .
        /// </summary>
        public static string NationalCodeRequired {
            get {
                return ResourceManager.GetString("NationalCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای ثبت نام کدملی الزامی می باشد.
        /// </summary>
        public static string NationalCodeRequiredForRegisteration {
            get {
                return ResourceManager.GetString("NationalCodeRequiredForRegisteration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلمه عبور وارد شده نامعتبر می باشد.
        /// </summary>
        public static string NewPasswordIsInvalid {
            get {
                return ResourceManager.GetString("NewPasswordIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما دسترسی به این قسمت ندارید .
        /// </summary>
        public static string NotAllowAccess {
            get {
                return ResourceManager.GetString("NotAllowAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان تغییر داده های سیستمی وجود ندارد.
        /// </summary>
        public static string NotAllowChange {
            get {
                return ResourceManager.GetString("NotAllowChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعاتی یافت نشد.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حداقل طول کلمه عبور شش کاراکتر می باشد.
        /// </summary>
        public static string PasswordMinLength {
            get {
                return ResourceManager.GetString("PasswordMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس ایمیل معتبر وارد نمائید.
        /// </summary>
        public static string Pleaseenteravalidemailaddress {
            get {
                return ResourceManager.GetString("Pleaseenteravalidemailaddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رزومه با موفقیت به لیست علاقه مندیها اضافه گردید.
        /// </summary>
        public static string ResumeToBookmarkSuccessfully {
            get {
                return ResourceManager.GetString("ResumeToBookmarkSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ابتدا اطلاعات مربوط با آگهی استخدام را ثبت کنید .
        /// </summary>
        public static string RrequiredEmploymentInfoFirst {
            get {
                return ResourceManager.GetString("RrequiredEmploymentInfoFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارسال ایمیل با موفقیت انجام گردید.
        /// </summary>
        public static string SendEmailSuccessfully {
            get {
                return ResourceManager.GetString("SendEmailSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلمه عبور با موفقیت به شماره همراه شما پیامک گردید.
        /// </summary>
        public static string SendSMSForForgotPasswordSuccessfully {
            get {
                return ResourceManager.GetString("SendSMSForForgotPasswordSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در ارسال کد اعتبارسنجی آدرس ایمیل .
        /// </summary>
        public static string SendVerifyCodeFailure {
            get {
                return ResourceManager.GetString("SendVerifyCodeFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارسال کد اعتبارسنجی آدرس ایمیل  با موفقیت انجام گردید..
        /// </summary>
        public static string SendVerifyCodeSuccessed {
            get {
                return ResourceManager.GetString("SendVerifyCodeSuccessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تایید.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملیات  با موفقیت انجام گردید..
        /// </summary>
        public static string Successd {
            get {
                return ResourceManager.GetString("Successd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آزمایش پیکربندی ارسال ایمیل با موفقیت انجام گردید.
        /// </summary>
        public static string SuccessedSendEmailForMailSettings {
            get {
                return ResourceManager.GetString("SuccessedSendEmailForMailSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to داده سیستمی.
        /// </summary>
        public static string SystemData {
            get {
                return ResourceManager.GetString("SystemData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to »».
        /// </summary>
        public static string TabsController_GetPageList_ {
            get {
                return ResourceManager.GetString("TabsController_GetPageList_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما قبلا این رزومه را به لیست علاقه مندیهای خود اضافه نموده اید.
        /// </summary>
        public static string ThereAreAlreadyResumeToBookmark {
            get {
                return ResourceManager.GetString("ThereAreAlreadyResumeToBookmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست شما با موفقیت بسته گردید.
        /// </summary>
        public static string TicketClosedSuccessfully {
            get {
                return ResourceManager.GetString("TicketClosedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست شما با موفقیت باز شد.
        /// </summary>
        public static string TicketOpenedSuccessfully {
            get {
                return ResourceManager.GetString("TicketOpenedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات پروفایل شما با موفقیت برروزرسانی گردید.
        /// </summary>
        public static string UpdatedProfile {
            get {
                return ResourceManager.GetString("UpdatedProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشخصات کاربری.
        /// </summary>
        public static string UserDetails {
            get {
                return ResourceManager.GetString("UserDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to منتظر بمانید.
        /// </summary>
        public static string Waiting {
            get {
                return ResourceManager.GetString("Waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هشدار.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما باید قوانین را قبول کنید.
        /// </summary>
        public static string YouMustApproveTermsCondition {
            get {
                return ResourceManager.GetString("YouMustApproveTermsCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیام شما با موفقیت بازیابی گردید..
        /// </summary>
        public static string YourMessageReceived {
            get {
                return ResourceManager.GetString("YourMessageReceived", resourceCulture);
            }
        }
    }
}
