//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nikan.Common.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ModelResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ModelResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nikan.Common.Resource.ModelResource", typeof(ModelResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملیات.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فعال.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس.
        /// </summary>
        public static string Addresss {
            get {
                return ResourceManager.GetString("Addresss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ساعت فعالبت.
        /// </summary>
        public static string BusinessHours {
            get {
                return ResourceManager.GetString("BusinessHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره تلفن دفتر.
        /// </summary>
        public static string CellNumber {
            get {
                return ResourceManager.GetString("CellNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت نمایش شهر.
        /// </summary>
        public static string CityActive {
            get {
                return ResourceManager.GetString("CityActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کدشهرستان.
        /// </summary>
        public static string CityCode {
            get {
                return ResourceManager.GetString("CityCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان شهرستان.
        /// </summary>
        public static string CityTitle {
            get {
                return ResourceManager.GetString("CityTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نظر.
        /// </summary>
        public static string CommentsDescription {
            get {
                return ResourceManager.GetString("CommentsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نظر خصوصی.
        /// </summary>
        public static string CommentsIsPrivate {
            get {
                return ResourceManager.GetString("CommentsIsPrivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ عضویت.
        /// </summary>
        public static string CreatedDateTime {
            get {
                return ResourceManager.GetString("CreatedDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ ایجاد.
        /// </summary>
        public static string CreateOnDate {
            get {
                return ResourceManager.GetString("CreateOnDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غیرفعال.
        /// </summary>
        public static string DeActive {
            get {
                return ResourceManager.GetString("DeActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توضیحات.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایمیل آدرس.
        /// </summary>
        public static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره فکس.
        /// </summary>
        public static string FaxNumber {
            get {
                return ResourceManager.GetString("FaxNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان پایین صفحه.
        /// </summary>
        public static string FooterText {
            get {
                return ResourceManager.GetString("FooterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to از تاریخ.
        /// </summary>
        public static string FromDate {
            get {
                return ResourceManager.GetString("FromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام و نام خانوادگی(اختیاری) .
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کامل سایت.
        /// </summary>
        public static string FullSiteName {
            get {
                return ResourceManager.GetString("FullSiteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیکن.
        /// </summary>
        public static string Icon {
            get {
                return ResourceManager.GetString("Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ترتیب نمایش.
        /// </summary>
        public static string IndexOrder {
            get {
                return ResourceManager.GetString("IndexOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فعال/غیرفعال.
        /// </summary>
        public static string IsActive {
            get {
                return ResourceManager.GetString("IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف شده ؟.
        /// </summary>
        public static string IsDeleted {
            get {
                return ResourceManager.GetString("IsDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سوال ویژه ؟.
        /// </summary>
        public static string IsMainFaq {
            get {
                return ResourceManager.GetString("IsMainFaq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خارج از قرارداد و وظایف.
        /// </summary>
        public static string IsSubtractFromContract {
            get {
                return ResourceManager.GetString("IsSubtractFromContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سیستمی.
        /// </summary>
        public static string IsSystem {
            get {
                return ResourceManager.GetString("IsSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایش عنوان شغلی.
        /// </summary>
        public static string JobIsActive {
            get {
                return ResourceManager.GetString("JobIsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تگ های مشابه عنوان شغلی.
        /// </summary>
        public static string JobTags {
            get {
                return ResourceManager.GetString("JobTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان شغل.
        /// </summary>
        public static string JobTitle {
            get {
                return ResourceManager.GetString("JobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آخرین مراجعه.
        /// </summary>
        public static string LastVisitDateTime {
            get {
                return ResourceManager.GetString("LastVisitDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلمه عبور.
        /// </summary>
        public static string MailServerPassword {
            get {
                return ResourceManager.GetString("MailServerPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درگاه.
        /// </summary>
        public static string MailServerPort {
            get {
                return ResourceManager.GetString("MailServerPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سرویس دهنده ایمیل.
        /// </summary>
        public static string MailServerUrl {
            get {
                return ResourceManager.GetString("MailServerUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه ورود .
        /// </summary>
        public static string MailServerUserName {
            get {
                return ResourceManager.GetString("MailServerUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رشته تحصیلی فعال است.
        /// </summary>
        public static string MajorIsActive {
            get {
                return ResourceManager.GetString("MajorIsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان رشته تحصیلی.
        /// </summary>
        public static string MajorTitle {
            get {
                return ResourceManager.GetString("MajorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حداکثر بازه حقوقی.
        /// </summary>
        public static string MaxRange {
            get {
                return ResourceManager.GetString("MaxRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حداقل بازه حقوقی.
        /// </summary>
        public static string MinRange {
            get {
                return ResourceManager.GetString("MinRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره موبایل.
        /// </summary>
        public static string MobileNumber {
            get {
                return ResourceManager.GetString("MobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطای اعتبارسنجی.
        /// </summary>
        public static string ModelStateError {
            get {
                return ResourceManager.GetString("ModelStateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to واحد.
        /// </summary>
        public static string OrganizationalUnitId {
            get {
                return ResourceManager.GetString("OrganizationalUnitId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان واحد.
        /// </summary>
        public static string OrganizationalUnitName {
            get {
                return ResourceManager.GetString("OrganizationalUnitName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سازمان.
        /// </summary>
        public static string OrganizationId {
            get {
                return ResourceManager.GetString("OrganizationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سازمان.
        /// </summary>
        public static string OrganizationName {
            get {
                return ResourceManager.GetString("OrganizationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دسته اصلی.
        /// </summary>
        public static string ParentId {
            get {
                return ResourceManager.GetString("ParentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان دسته شغلی.
        /// </summary>
        public static string ParentJobTitle {
            get {
                return ResourceManager.GetString("ParentJobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پاسخ سوال.
        /// </summary>
        public static string QuestionDescription {
            get {
                return ResourceManager.GetString("QuestionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گروه سوال.
        /// </summary>
        public static string QuestionGroupTypeId {
            get {
                return ResourceManager.GetString("QuestionGroupTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت سوال.
        /// </summary>
        public static string QuestionStatus {
            get {
                return ResourceManager.GetString("QuestionStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان سوال.
        /// </summary>
        public static string QuestionTitle {
            get {
                return ResourceManager.GetString("QuestionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان رنج حقوقی.
        /// </summary>
        public static string RangeTitle {
            get {
                return ResourceManager.GetString("RangeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فیلد {0} الزامی می باشد.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلید واحد جستجو.
        /// </summary>
        public static string SearchTitle {
            get {
                return ResourceManager.GetString("SearchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد مشترک عنوان شغلی.
        /// </summary>
        public static string ShJobCode {
            get {
                return ResourceManager.GetString("ShJobCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توضیحات سئو.
        /// </summary>
        public static string SiteDescription {
            get {
                return ResourceManager.GetString("SiteDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلمات کلیدی.
        /// </summary>
        public static string SiteKeywords {
            get {
                return ResourceManager.GetString("SiteKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام سایت.
        /// </summary>
        public static string SiteName {
            get {
                return ResourceManager.GetString("SiteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس سایت.
        /// </summary>
        public static string SiteUrl {
            get {
                return ResourceManager.GetString("SiteUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت نمایش مهارت.
        /// </summary>
        public static string SkillIsActive {
            get {
                return ResourceManager.GetString("SkillIsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان مهارت.
        /// </summary>
        public static string SkillTitle {
            get {
                return ResourceManager.GetString("SkillTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلمه جستجو.
        /// </summary>
        public static string Slug {
            get {
                return ResourceManager.GetString("Slug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره پیامک.
        /// </summary>
        public static string SMSNumber {
            get {
                return ResourceManager.GetString("SMSNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلمات کلیدی.
        /// </summary>
        public static string TagNames {
            get {
                return ResourceManager.GetString("TagNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس کانال تلگرام.
        /// </summary>
        public static string TelegramChannelId {
            get {
                return ResourceManager.GetString("TelegramChannelId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مسیر تصویر.
        /// </summary>
        public static string ThumbUrl {
            get {
                return ResourceManager.GetString("ThumbUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شرح فعالیت.
        /// </summary>
        public static string TicketActivityDescription {
            get {
                return ResourceManager.GetString("TicketActivityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس ایمیل (اختیاری).
        /// </summary>
        public static string TicketEmail {
            get {
                return ResourceManager.GetString("TicketEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متن پیام (اجباری).
        /// </summary>
        public static string TicketMessage {
            get {
                return ResourceManager.GetString("TicketMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره تلفن(اختیاری).
        /// </summary>
        public static string TicketPhone {
            get {
                return ResourceManager.GetString("TicketPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اولویت درخواست.
        /// </summary>
        public static string TicketPriority {
            get {
                return ResourceManager.GetString("TicketPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بخش تیکت.
        /// </summary>
        public static string TicketSection {
            get {
                return ResourceManager.GetString("TicketSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to همه درخواست ها.
        /// </summary>
        public static string TicketStatusEnum_All {
            get {
                return ResourceManager.GetString("TicketStatusEnum_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پاسخ داده شده.
        /// </summary>
        public static string TicketStatusEnum_Answered {
            get {
                return ResourceManager.GetString("TicketStatusEnum_Answered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسته شده.
        /// </summary>
        public static string TicketStatusEnum_Closed {
            get {
                return ResourceManager.GetString("TicketStatusEnum_Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بایگانی شده.
        /// </summary>
        public static string TicketStatusEnum_IsArchive {
            get {
                return ResourceManager.GetString("TicketStatusEnum_IsArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جدید.
        /// </summary>
        public static string TicketStatusEnum_New {
            get {
                return ResourceManager.GetString("TicketStatusEnum_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حل شد.
        /// </summary>
        public static string TicketStatusEnum_Solved {
            get {
                return ResourceManager.GetString("TicketStatusEnum_Solved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در دست بررسی.
        /// </summary>
        public static string TicketStatusEnum_UnderReview {
            get {
                return ResourceManager.GetString("TicketStatusEnum_UnderReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان درخواست.
        /// </summary>
        public static string TicketTitle {
            get {
                return ResourceManager.GetString("TicketTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع درخواست.
        /// </summary>
        public static string TicketType {
            get {
                return ResourceManager.GetString("TicketType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تا.
        /// </summary>
        public static string ToDate {
            get {
                return ResourceManager.GetString("ToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارسال کننده.
        /// </summary>
        public static string UserOwnerId {
            get {
                return ResourceManager.GetString("UserOwnerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نقش های کاربر.
        /// </summary>
        public static string UserRoles {
            get {
                return ResourceManager.GetString("UserRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت کاربری.
        /// </summary>
        public static string UserStatues {
            get {
                return ResourceManager.GetString("UserStatues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد مشاهده.
        /// </summary>
        public static string ViewCount {
            get {
                return ResourceManager.GetString("ViewCount", resourceCulture);
            }
        }
    }
}
