//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bpmellat.co/")]
    public partial class ServiceException
    {
        
        private string messageStateField;
        
        private string[] paramsField;
        
        private int messageCodeField;
        
        private bool messageCodeFieldSpecified;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string messageState
        {
            get
            {
                return this.messageStateField;
            }
            set
            {
                this.messageStateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("params", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string[] @params
        {
            get
            {
                return this.paramsField;
            }
            set
            {
                this.paramsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int messageCode
        {
            get
            {
                return this.messageCodeField;
            }
            set
            {
                this.messageCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool messageCodeSpecified
        {
            get
            {
                return this.messageCodeFieldSpecified;
            }
            set
            {
                this.messageCodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://bpmellat.co/", ConfigurationName="ServiceReference1.TransactionService")]
    public interface TransactionService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bpmellat.co/getBillPaymentByDate", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.ServiceException), Action="http://bpmellat.co/getBillPaymentByDate", Name="ServiceException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> getBillPaymentByDateAsync(long TerminalId, int FromDate, int ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bpmellat.co/getRefundTransactionByRefrenceId", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.ServiceException), Action="http://bpmellat.co/getRefundTransactionByRefrenceId", Name="ServiceException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> getRefundTransactionByRefrenceIdAsync(long refundRefrenceId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bpmellat.co/getBillPaymentBank", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.ServiceException), Action="http://bpmellat.co/getBillPaymentBank", Name="ServiceException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> getBillPaymentBankAsync(int transactionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bpmellat.co/getShetabInfoById", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.ServiceException), Action="http://bpmellat.co/getShetabInfoById", Name="ServiceException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> getShetabInfoByIdAsync(long referenceId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bpmellat.co/getTransactionByCustomerBranchId", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.ServiceException), Action="http://bpmellat.co/getTransactionByCustomerBranchId", Name="ServiceException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getTransactionByCustomerBranchId")]
        System.Threading.Tasks.Task<string> getTransactionByCustomerBranchIdAsync(long customerBranchId, int fromDate, int toDate, long fromRecordId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bpmellat.co/getRefundTransactionWithCommissionByDateNew", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.ServiceException), Action="http://bpmellat.co/getRefundTransactionWithCommissionByDateNew", Name="ServiceException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getRefundTransactionWithCommissionByDateNew")]
        System.Threading.Tasks.Task<string> getRefundTransactionWithCommissionByDateNewAsync(int fromDate, int toDate, int terminalId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bpmellat.co/getTransactionStatusByTerminalIdAndOrderId", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.ServiceException), Action="http://bpmellat.co/getTransactionStatusByTerminalIdAndOrderId", Name="ServiceException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getTransactionStatusByTerminalIdAndOrderId")]
        System.Threading.Tasks.Task<string> getTransactionStatusByTerminalIdAndOrderIdAsync(long terminalId, long orderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bpmellat.co/getDiscountTransactionByDate", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.ServiceException), Action="http://bpmellat.co/getDiscountTransactionByDate", Name="ServiceException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getDiscountTransactionByDate")]
        System.Threading.Tasks.Task<string> getDiscountTransactionByDateAsync(long terminalId, int fromDate, int toDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bpmellat.co/getRefundTransactionWithCommissionByIdNew", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.ServiceException), Action="http://bpmellat.co/getRefundTransactionWithCommissionByIdNew", Name="ServiceException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getRefundTransactionWithCommissionByIdNew")]
        System.Threading.Tasks.Task<string> getRefundTransactionWithCommissionByIdNewAsync(long saleRefrenceId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bpmellat.co/getTransactionByCustomerId", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.ServiceException), Action="http://bpmellat.co/getTransactionByCustomerId", Name="ServiceException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> getTransactionByCustomerIdAsync(long customerId, int fromDate, int toDate, long fromRecordId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bpmellat.co/getTransactionByDiscountInquiryId", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.ServiceException), Action="http://bpmellat.co/getTransactionByDiscountInquiryId", Name="ServiceException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> getTransactionByDiscountInquiryIdAsync(long discountInquiryId, int date, long PAN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bpmellat.co/getCardsInfo", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.ServiceException), Action="http://bpmellat.co/getCardsInfo", Name="ServiceException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getCardsInfo")]
        System.Threading.Tasks.Task<string> getCardsInfoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bpmellat.co/getTransactionByIdFromArchive", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.ServiceException), Action="http://bpmellat.co/getTransactionByIdFromArchive", Name="ServiceException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> getTransactionByIdFromArchiveAsync(long referenceId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bpmellat.co/getTransactionByBillIdAndPayId", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.ServiceException), Action="http://bpmellat.co/getTransactionByBillIdAndPayId", Name="ServiceException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> getTransactionByBillIdAndPayIdAsync(long billId, long payId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bpmellat.co/getTransactionById", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.ServiceException), Action="http://bpmellat.co/getTransactionById", Name="ServiceException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> getTransactionByIdAsync(long referenceId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bpmellat.co/getTransactionByPayerId", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.ServiceException), Action="http://bpmellat.co/getTransactionByPayerId", Name="ServiceException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.getTransactionByPayerIdResponse> getTransactionByPayerIdAsync(ServiceReference1.getTransactionByPayerId request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bpmellat.co/getRefundTransactionByRefrenceIdNew", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.ServiceException), Action="http://bpmellat.co/getRefundTransactionByRefrenceIdNew", Name="ServiceException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getRefundTransactionByRefrenceIdResultNew")]
        System.Threading.Tasks.Task<string> getRefundTransactionByRefrenceIdNewAsync(long saleRefrenceId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bpmellat.co/getRefundTransactionWithCommissionByDate", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.ServiceException), Action="http://bpmellat.co/getRefundTransactionWithCommissionByDate", Name="ServiceException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getRefundTransactionWithCommissionByDate")]
        System.Threading.Tasks.Task<string> getRefundTransactionWithCommissionByDateAsync(int fromDate, int toDate, int terminalId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bpmellat.co/getInstituteTransactionByDate", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.ServiceException), Action="http://bpmellat.co/getInstituteTransactionByDate", Name="ServiceException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getInstituteTransactionByDate")]
        System.Threading.Tasks.Task<string> getInstituteTransactionByDateAsync(string iban, int createDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bpmellat.co/getBillPaymentHamrahAvalBANK", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.ServiceException), Action="http://bpmellat.co/getBillPaymentHamrahAvalBANK", Name="ServiceException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> getBillPaymentHamrahAvalBANKAsync(long transactionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bpmellat.co/getBillShaparkForPostByIbanAndDate", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.ServiceException), Action="http://bpmellat.co/getBillShaparkForPostByIbanAndDate", Name="ServiceException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getBillShaparkForPostByIbanAndDateResult")]
        System.Threading.Tasks.Task<string> getPostDepositDraftByIbanAsync(int draftDate, string iban);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bpmellat.co/changeRequest", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.ServiceException), Action="http://bpmellat.co/changeRequest", Name="ServiceException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="changeRequest")]
        System.Threading.Tasks.Task<string> changeRequestAsync(long userId, int terminalId, long newAccountNo, string currentAccount, string newIban);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bpmellat.co/getTerminalsInfo", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.ServiceException), Action="http://bpmellat.co/getTerminalsInfo", Name="ServiceException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getTerminalsInfo")]
        System.Threading.Tasks.Task<string> getTerminalsInfoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bpmellat.co/getBillPaymentPSP", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.ServiceException), Action="http://bpmellat.co/getBillPaymentPSP", Name="ServiceException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> getBillPaymentPSPAsync(int transactionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bpmellat.co/getTransactionStatusByIdFromArchive", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.ServiceException), Action="http://bpmellat.co/getTransactionStatusByIdFromArchive", Name="ServiceException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getTransactionStatusByIdFromArchive")]
        System.Threading.Tasks.Task<string> getTransactionStatusByIdFromArchiveAsync(long referenceId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bpmellat.co/getTransactionByDiscountInquiryIdFromArchive", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.ServiceException), Action="http://bpmellat.co/getTransactionByDiscountInquiryIdFromArchive", Name="ServiceException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> getTransactionByDiscountInquiryIdFromArchiveAsync(long discountInquiryId, int date, long PAN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bpmellat.co/getTransactionByTerminalIdAndOrderId", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.ServiceException), Action="http://bpmellat.co/getTransactionByTerminalIdAndOrderId", Name="ServiceException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> getTransactionByTerminalIdAndOrderIdAsync(long terminalId, long orderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bpmellat.co/getPosTerminalRequest", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.ServiceException), Action="http://bpmellat.co/getPosTerminalRequest", Name="ServiceException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> getPosTerminalRequestAsync(int createDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bpmellat.co/getBillPaymentHamrahAvalPSP", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.ServiceException), Action="http://bpmellat.co/getBillPaymentHamrahAvalPSP", Name="ServiceException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> getBillPaymentHamrahAvalPSPAsync(long transactionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bpmellat.co/getRefundBalance", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.ServiceException), Action="http://bpmellat.co/getRefundBalance", Name="ServiceException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> getRefundBalanceAsync(int terminalId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bpmellat.co/getTransactionByRRNAndTerminalId", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.ServiceException), Action="http://bpmellat.co/getTransactionByRRNAndTerminalId", Name="ServiceException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> getTransactionByRRNAndTerminalIdAsync(long terminalId, long rrn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bpmellat.co/getRefundTransactionByDate", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.ServiceException), Action="http://bpmellat.co/getRefundTransactionByDate", Name="ServiceException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> getRefundTransactionByDateAsync(int createDate, int terminalId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bpmellat.co/getUnsuccessfulTransactionsByDate", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.ServiceException), Action="http://bpmellat.co/getUnsuccessfulTransactionsByDate", Name="ServiceException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getUnsuccessfulTransactionsByDate")]
        System.Threading.Tasks.Task<string> getUnsuccessfulTransactionsByDateAsync(long terminalId, int fromDate, int toDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bpmellat.co/getTransactionGeneralByBillIdAndPayId", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.ServiceException), Action="http://bpmellat.co/getTransactionGeneralByBillIdAndPayId", Name="ServiceException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getGeneralBillInfo")]
        System.Threading.Tasks.Task<string> getGeneralBillInfoAsync(long billId, long payId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bpmellat.co/getRequestStatus", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.ServiceException), Action="http://bpmellat.co/getRequestStatus", Name="ServiceException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> getRequestStatusAsync(int createDate, string nationalityCode, short terminalType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bpmellat.co/getOfferTransactionByDate", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.ServiceException), Action="http://bpmellat.co/getOfferTransactionByDate", Name="ServiceException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> getOfferTransactionByDateAsync(long terminalId, int fromDate, int toDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bpmellat.co/getOnlineTransactionByDate", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.ServiceException), Action="http://bpmellat.co/getOnlineTransactionByDate", Name="ServiceException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getOnlineTransactionByDate")]
        System.Threading.Tasks.Task<string> getOnlineTransactionByDateAsync(long terminalId, int date, long afterRowNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bpmellat.co/getTransactionByDate", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.ServiceException), Action="http://bpmellat.co/getTransactionByDate", Name="ServiceException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> getTransactionByDateAsync(long TerminalId, int FromDate, int ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bpmellat.co/getTransactionStatusById", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.ServiceException), Action="http://bpmellat.co/getTransactionStatusById", Name="ServiceException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getTransactionStatusById")]
        System.Threading.Tasks.Task<string> getTransactionStatusByIdAsync(long referenceId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bpmellat.co/getRefundTransactionByOrderId", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.ServiceException), Action="http://bpmellat.co/getRefundTransactionByOrderId", Name="ServiceException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getRefundTransactionByOrderId")]
        System.Threading.Tasks.Task<string> getRefundTransactionByOrderIdAsync(long orderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bpmellat.co/getRefundTransactionByDateNew", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.ServiceException), Action="http://bpmellat.co/getRefundTransactionByDateNew", Name="ServiceException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getRefundTransactionByDateResultNew")]
        System.Threading.Tasks.Task<string> getRefundTransactionByDateNewAsync(int createDate, int terminalId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bpmellat.co/getTransactionByBillIdAndPayIdFromArchive", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.ServiceException), Action="http://bpmellat.co/getTransactionByBillIdAndPayIdFromArchive", Name="ServiceException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> getTransactionByBillIdAndPayIdFromArchiveAsync(long billId, long payId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bpmellat.co/getTransactionByIdWithCardType", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.ServiceException), Action="http://bpmellat.co/getTransactionByIdWithCardType", Name="ServiceException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getTransactionByIdWithCardType")]
        System.Threading.Tasks.Task<string> getTransactionByIdWithCardTypeAsync(long referenceId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bpmellat.co/getDepositDraftByIban", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.ServiceException), Action="http://bpmellat.co/getDepositDraftByIban", Name="ServiceException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> getDepositDraftByIbanAsync(int DraftDate, string Iban);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bpmellat.co/getMobileTransactions", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.ServiceException), Action="http://bpmellat.co/getMobileTransactions", Name="ServiceException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getMobileTransactions")]
        System.Threading.Tasks.Task<string> getMobileTransactionsAsync(int terminalId, int createDate, long mobile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bpmellat.co/getRefundTransactionWithCommissionById", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.ServiceException), Action="http://bpmellat.co/getRefundTransactionWithCommissionById", Name="ServiceException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getRefundTransactionWithCommissionById")]
        System.Threading.Tasks.Task<string> getRefundTransactionWithCommissionByIdAsync(long refundRefrenceId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bpmellat.co/getTransactionByIdForRefund", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.ServiceException), Action="http://bpmellat.co/getTransactionByIdForRefund", Name="ServiceException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> getTransactionByIdForRefundAsync(long referenceId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bpmellat.co/getTransactionInquiryByCustomer", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.ServiceException), Action="http://bpmellat.co/getTransactionInquiryByCustomer", Name="ServiceException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getTransactionInquiryByCustomer")]
        System.Threading.Tasks.Task<string> getTransactionInquiryByCustomerAsync(long transactionId, string transactionDate, int terminalId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bpmellat.co/getChangeAccountInquiryRequestStatus", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.ServiceException), Action="http://bpmellat.co/getChangeAccountInquiryRequestStatus", Name="ServiceException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> getChangeAccountInquiryRequestStatusAsync(int terminalId, string oldValue, string oldIban);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getTransactionByPayerId", WrapperNamespace="http://bpmellat.co/", IsWrapped=true)]
    public partial class getTransactionByPayerId
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bpmellat.co/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string payerId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bpmellat.co/", Order=1)]
        public int persianDate;
        
        public getTransactionByPayerId()
        {
        }
        
        public getTransactionByPayerId(string payerId, int persianDate)
        {
            this.payerId = payerId;
            this.persianDate = persianDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getTransactionByPayerIdResponse", WrapperNamespace="http://bpmellat.co/", IsWrapped=true)]
    public partial class getTransactionByPayerIdResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bpmellat.co/", Order=0)]
        public string getTransactionByPayerId;
        
        public getTransactionByPayerIdResponse()
        {
        }
        
        public getTransactionByPayerIdResponse(string getTransactionByPayerId)
        {
            this.getTransactionByPayerId = getTransactionByPayerId;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface TransactionServiceChannel : ServiceReference1.TransactionService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class TransactionServiceClient : System.ServiceModel.ClientBase<ServiceReference1.TransactionService>, ServiceReference1.TransactionService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public TransactionServiceClient() : 
                base(TransactionServiceClient.GetDefaultBinding(), TransactionServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.TransactionServiceImplPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TransactionServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(TransactionServiceClient.GetBindingForEndpoint(endpointConfiguration), TransactionServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TransactionServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(TransactionServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TransactionServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(TransactionServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TransactionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<string> getBillPaymentByDateAsync(long TerminalId, int FromDate, int ToDate)
        {
            return base.Channel.getBillPaymentByDateAsync(TerminalId, FromDate, ToDate);
        }
        
        public System.Threading.Tasks.Task<string> getRefundTransactionByRefrenceIdAsync(long refundRefrenceId)
        {
            return base.Channel.getRefundTransactionByRefrenceIdAsync(refundRefrenceId);
        }
        
        public System.Threading.Tasks.Task<string> getBillPaymentBankAsync(int transactionId)
        {
            return base.Channel.getBillPaymentBankAsync(transactionId);
        }
        
        public System.Threading.Tasks.Task<string> getShetabInfoByIdAsync(long referenceId)
        {
            return base.Channel.getShetabInfoByIdAsync(referenceId);
        }
        
        public System.Threading.Tasks.Task<string> getTransactionByCustomerBranchIdAsync(long customerBranchId, int fromDate, int toDate, long fromRecordId)
        {
            return base.Channel.getTransactionByCustomerBranchIdAsync(customerBranchId, fromDate, toDate, fromRecordId);
        }
        
        public System.Threading.Tasks.Task<string> getRefundTransactionWithCommissionByDateNewAsync(int fromDate, int toDate, int terminalId)
        {
            return base.Channel.getRefundTransactionWithCommissionByDateNewAsync(fromDate, toDate, terminalId);
        }
        
        public System.Threading.Tasks.Task<string> getTransactionStatusByTerminalIdAndOrderIdAsync(long terminalId, long orderId)
        {
            return base.Channel.getTransactionStatusByTerminalIdAndOrderIdAsync(terminalId, orderId);
        }
        
        public System.Threading.Tasks.Task<string> getDiscountTransactionByDateAsync(long terminalId, int fromDate, int toDate)
        {
            return base.Channel.getDiscountTransactionByDateAsync(terminalId, fromDate, toDate);
        }
        
        public System.Threading.Tasks.Task<string> getRefundTransactionWithCommissionByIdNewAsync(long saleRefrenceId)
        {
            return base.Channel.getRefundTransactionWithCommissionByIdNewAsync(saleRefrenceId);
        }
        
        public System.Threading.Tasks.Task<string> getTransactionByCustomerIdAsync(long customerId, int fromDate, int toDate, long fromRecordId)
        {
            return base.Channel.getTransactionByCustomerIdAsync(customerId, fromDate, toDate, fromRecordId);
        }
        
        public System.Threading.Tasks.Task<string> getTransactionByDiscountInquiryIdAsync(long discountInquiryId, int date, long PAN)
        {
            return base.Channel.getTransactionByDiscountInquiryIdAsync(discountInquiryId, date, PAN);
        }
        
        public System.Threading.Tasks.Task<string> getCardsInfoAsync()
        {
            return base.Channel.getCardsInfoAsync();
        }
        
        public System.Threading.Tasks.Task<string> getTransactionByIdFromArchiveAsync(long referenceId)
        {
            return base.Channel.getTransactionByIdFromArchiveAsync(referenceId);
        }
        
        public System.Threading.Tasks.Task<string> getTransactionByBillIdAndPayIdAsync(long billId, long payId)
        {
            return base.Channel.getTransactionByBillIdAndPayIdAsync(billId, payId);
        }
        
        public System.Threading.Tasks.Task<string> getTransactionByIdAsync(long referenceId)
        {
            return base.Channel.getTransactionByIdAsync(referenceId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.getTransactionByPayerIdResponse> ServiceReference1.TransactionService.getTransactionByPayerIdAsync(ServiceReference1.getTransactionByPayerId request)
        {
            return base.Channel.getTransactionByPayerIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.getTransactionByPayerIdResponse> getTransactionByPayerIdAsync(string payerId, int persianDate)
        {
            ServiceReference1.getTransactionByPayerId inValue = new ServiceReference1.getTransactionByPayerId();
            inValue.payerId = payerId;
            inValue.persianDate = persianDate;
            return ((ServiceReference1.TransactionService)(this)).getTransactionByPayerIdAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<string> getRefundTransactionByRefrenceIdNewAsync(long saleRefrenceId)
        {
            return base.Channel.getRefundTransactionByRefrenceIdNewAsync(saleRefrenceId);
        }
        
        public System.Threading.Tasks.Task<string> getRefundTransactionWithCommissionByDateAsync(int fromDate, int toDate, int terminalId)
        {
            return base.Channel.getRefundTransactionWithCommissionByDateAsync(fromDate, toDate, terminalId);
        }
        
        public System.Threading.Tasks.Task<string> getInstituteTransactionByDateAsync(string iban, int createDate)
        {
            return base.Channel.getInstituteTransactionByDateAsync(iban, createDate);
        }
        
        public System.Threading.Tasks.Task<string> getBillPaymentHamrahAvalBANKAsync(long transactionId)
        {
            return base.Channel.getBillPaymentHamrahAvalBANKAsync(transactionId);
        }
        
        public System.Threading.Tasks.Task<string> getPostDepositDraftByIbanAsync(int draftDate, string iban)
        {
            return base.Channel.getPostDepositDraftByIbanAsync(draftDate, iban);
        }
        
        public System.Threading.Tasks.Task<string> changeRequestAsync(long userId, int terminalId, long newAccountNo, string currentAccount, string newIban)
        {
            return base.Channel.changeRequestAsync(userId, terminalId, newAccountNo, currentAccount, newIban);
        }
        
        public System.Threading.Tasks.Task<string> getTerminalsInfoAsync()
        {
            return base.Channel.getTerminalsInfoAsync();
        }
        
        public System.Threading.Tasks.Task<string> getBillPaymentPSPAsync(int transactionId)
        {
            return base.Channel.getBillPaymentPSPAsync(transactionId);
        }
        
        public System.Threading.Tasks.Task<string> getTransactionStatusByIdFromArchiveAsync(long referenceId)
        {
            return base.Channel.getTransactionStatusByIdFromArchiveAsync(referenceId);
        }
        
        public System.Threading.Tasks.Task<string> getTransactionByDiscountInquiryIdFromArchiveAsync(long discountInquiryId, int date, long PAN)
        {
            return base.Channel.getTransactionByDiscountInquiryIdFromArchiveAsync(discountInquiryId, date, PAN);
        }
        
        public System.Threading.Tasks.Task<string> getTransactionByTerminalIdAndOrderIdAsync(long terminalId, long orderId)
        {
            return base.Channel.getTransactionByTerminalIdAndOrderIdAsync(terminalId, orderId);
        }
        
        public System.Threading.Tasks.Task<string> getPosTerminalRequestAsync(int createDate)
        {
            return base.Channel.getPosTerminalRequestAsync(createDate);
        }
        
        public System.Threading.Tasks.Task<string> getBillPaymentHamrahAvalPSPAsync(long transactionId)
        {
            return base.Channel.getBillPaymentHamrahAvalPSPAsync(transactionId);
        }
        
        public System.Threading.Tasks.Task<string> getRefundBalanceAsync(int terminalId)
        {
            return base.Channel.getRefundBalanceAsync(terminalId);
        }
        
        public System.Threading.Tasks.Task<string> getTransactionByRRNAndTerminalIdAsync(long terminalId, long rrn)
        {
            return base.Channel.getTransactionByRRNAndTerminalIdAsync(terminalId, rrn);
        }
        
        public System.Threading.Tasks.Task<string> getRefundTransactionByDateAsync(int createDate, int terminalId)
        {
            return base.Channel.getRefundTransactionByDateAsync(createDate, terminalId);
        }
        
        public System.Threading.Tasks.Task<string> getUnsuccessfulTransactionsByDateAsync(long terminalId, int fromDate, int toDate)
        {
            return base.Channel.getUnsuccessfulTransactionsByDateAsync(terminalId, fromDate, toDate);
        }
        
        public System.Threading.Tasks.Task<string> getGeneralBillInfoAsync(long billId, long payId)
        {
            return base.Channel.getGeneralBillInfoAsync(billId, payId);
        }
        
        public System.Threading.Tasks.Task<string> getRequestStatusAsync(int createDate, string nationalityCode, short terminalType)
        {
            return base.Channel.getRequestStatusAsync(createDate, nationalityCode, terminalType);
        }
        
        public System.Threading.Tasks.Task<string> getOfferTransactionByDateAsync(long terminalId, int fromDate, int toDate)
        {
            return base.Channel.getOfferTransactionByDateAsync(terminalId, fromDate, toDate);
        }
        
        public System.Threading.Tasks.Task<string> getOnlineTransactionByDateAsync(long terminalId, int date, long afterRowNumber)
        {
            return base.Channel.getOnlineTransactionByDateAsync(terminalId, date, afterRowNumber);
        }
        
        public System.Threading.Tasks.Task<string> getTransactionByDateAsync(long TerminalId, int FromDate, int ToDate)
        {
            return base.Channel.getTransactionByDateAsync(TerminalId, FromDate, ToDate);
        }
        
        public System.Threading.Tasks.Task<string> getTransactionStatusByIdAsync(long referenceId)
        {
            return base.Channel.getTransactionStatusByIdAsync(referenceId);
        }
        
        public System.Threading.Tasks.Task<string> getRefundTransactionByOrderIdAsync(long orderId)
        {
            return base.Channel.getRefundTransactionByOrderIdAsync(orderId);
        }
        
        public System.Threading.Tasks.Task<string> getRefundTransactionByDateNewAsync(int createDate, int terminalId)
        {
            return base.Channel.getRefundTransactionByDateNewAsync(createDate, terminalId);
        }
        
        public System.Threading.Tasks.Task<string> getTransactionByBillIdAndPayIdFromArchiveAsync(long billId, long payId)
        {
            return base.Channel.getTransactionByBillIdAndPayIdFromArchiveAsync(billId, payId);
        }
        
        public System.Threading.Tasks.Task<string> getTransactionByIdWithCardTypeAsync(long referenceId)
        {
            return base.Channel.getTransactionByIdWithCardTypeAsync(referenceId);
        }
        
        public System.Threading.Tasks.Task<string> getDepositDraftByIbanAsync(int DraftDate, string Iban)
        {
            return base.Channel.getDepositDraftByIbanAsync(DraftDate, Iban);
        }
        
        public System.Threading.Tasks.Task<string> getMobileTransactionsAsync(int terminalId, int createDate, long mobile)
        {
            return base.Channel.getMobileTransactionsAsync(terminalId, createDate, mobile);
        }
        
        public System.Threading.Tasks.Task<string> getRefundTransactionWithCommissionByIdAsync(long refundRefrenceId)
        {
            return base.Channel.getRefundTransactionWithCommissionByIdAsync(refundRefrenceId);
        }
        
        public System.Threading.Tasks.Task<string> getTransactionByIdForRefundAsync(long referenceId)
        {
            return base.Channel.getTransactionByIdForRefundAsync(referenceId);
        }
        
        public System.Threading.Tasks.Task<string> getTransactionInquiryByCustomerAsync(long transactionId, string transactionDate, int terminalId)
        {
            return base.Channel.getTransactionInquiryByCustomerAsync(transactionId, transactionDate, terminalId);
        }
        
        public System.Threading.Tasks.Task<string> getChangeAccountInquiryRequestStatusAsync(int terminalId, string oldValue, string oldIban)
        {
            return base.Channel.getChangeAccountInquiryRequestStatusAsync(terminalId, oldValue, oldIban);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.TransactionServiceImplPort))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.TransactionServiceImplPort))
            {
                return new System.ServiceModel.EndpointAddress("http://bos.bpm.bankmellat.ir/backoffice/Services/bpm/TransactionService.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return TransactionServiceClient.GetBindingForEndpoint(EndpointConfiguration.TransactionServiceImplPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return TransactionServiceClient.GetEndpointAddress(EndpointConfiguration.TransactionServiceImplPort);
        }
        
        public enum EndpointConfiguration
        {
            
            TransactionServiceImplPort,
        }
    }
}
